plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.2'
}

apply plugin: 'io.spring.dependency-management'

java {
    sourceCompatibility = '21'
}

repositories {
    mavenCentral()
}

dependencies {

    implementation 'com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.14.3'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.14.3'

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.redisson:redisson-spring-boot-starter:3.17.0'
    implementation 'com.giffing.bucket4j.spring.boot.starter:bucket4j-spring-boot-starter:0.5.2'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.testcontainers:testcontainers:1.20.2'
    testImplementation "org.testcontainers:junit-jupiter:1.20.2"
}

test {
    useJUnitPlatform()
}
